### ISSUE TITLE
Provided structured description of ECO usages on OBO metadata

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#148]
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/451

**Comment by cmungall** [comment]
I added an example for GO - if you can provide more, preferable with a URL with ECO in the URL

**Comment by rctauber** [comment]
Hi @cmungall - how many usage examples do you need? We have a whole list of users at http://evidenceontology.org/about_us/#usergroups

For example (let me know if this is what you're looking for and I can provide more):
```
 - user: http://www.ebi.ac.uk/GOA
   type: annotation
   description: ECO is used by the UniProt Gene Ontology Annotation (UniProt-GOA) Database to provide annotations to proteins in the UniProt Knowledgebase.
   examples:
    - url: http://www.ebi.ac.uk/QuickGO/term/ECO:0000256
      description: automated annotations from matches to sequence models
  ```
