### ISSUE TITLE
Which browser should be the default for ECO?

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#271]
OBO PURLs redirect to Ontobee

GO uses the eco browser 

https://github.com/geneontology/go-site/blob/12f2a3850473d901a7112d3b7ce8c5b2316be83e/metadata/db-xrefs.yaml#L567-L578

See also jira.atlassian.net/browse/AGR-2434

the OBO page for ECO lists 3 possible browsers but not the ECO one

http://obofoundry.org/ontology/eco

It seems like ECO's preferred browser is your own one? Can you confirm that this includes all necessary information compared to OLS/OntoBee?

If this is your preferred browser then I suggest

 - configuring your OBO PURLs to redirect to it
 - adding a button on the OBO page

cc @lpalbou

**Comment by mgiglio99** [comment]
Hi Chris,
Thanks for pointing this out. We will get it all sorted and pointing correctly.
Michelle

**Comment by mgiglio99** [comment]
Hi @cmungall 
@nsuvarnaiari  and I have a few questions about which places we need to update.
Becky would normally help us with this, but she is out on maternity leave.
Do you have a few minutes to direct us?

**Comment by nsuvarnaiari** [comment]
Hi @cmungall and @lpalbou

Michelle and I have decided to redirect OBO PURLs to OLS instead of OntoBee (we do not want ECO browser either). OLS's ECO browser page has all the necessary information so should be ideal for OBO PURLs. I changed the config file [eco.yml](https://github.com/OBOFoundry/purl.obolibrary.org/edit/master/config/eco.yml) to that effect, but did not initiate a PR. I am not 100% sure if I did it correct. Sending you a screenshot of eco.yml page with the changes marked with black line. Please take a look and let me know if those are the two places I need to change and if the content is correct.

And, I could not figure out how to add [eco browser](https://evidenceontology.org/browse/) button on the OBO page. Could you please help us add the button?

![Screen Shot 2022-09-14 at 4 08 56 PM](https://user-images.githubusercontent.com/13201743/190258999-1e61eeec-4c96-44dd-80e8-7a5ef89133ef.png)

 Thanks,
Suvvi and @mgiglio99

**Comment by mgiglio99** [comment]
Hi  @cmungall and @lpalbou
Just wanted to see if you saw this - we're hoping to finish this task up.
Thanks,
Michelle

**Comment by mgiglio99** [comment]
Hi again @cmungall and @Ipalbou
Just pinging this issue again.
Next I'll try email or slack to ask about these questions as we're not sure how to proceed to resolve this.
Thanks : )

**Comment by allenbaron** [comment]
To make term PURLS redirect to OLS you only have to set `term browser: ols` as you have ([MONDO](https://github.com/OBOFoundry/purl.obolibrary.org/blob/22e9e46e64b63bb9eecd4ae60ab4e60e8db53c5e/config/mondo.yml#L11) example). If you want to keep the `/about/` redirects (not required) you'll need to use OLS4 as the old OLS has been deprecated. Update the [respective yaml lines](https://github.com/OBOFoundry/purl.obolibrary.org/blob/22e9e46e64b63bb9eecd4ae60ab4e60e8db53c5e/config/eco.yml#L24-L28) as follows:

ONTOBEE (current)
```yml
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=ECO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/ECO_0000000
    to: http://www.ontobee.org/browser/rdf.php?o=ECO&iri=http://purl.obolibrary.org/obo/ECO_0000000
```

OLS
```yml
- prefix: /about/
  replacement: https://www.ebi.ac.uk/ols4/ontologies/eco/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252F
  tests:
  - from: /about/ECO_0000000
    to: https://www.ebi.ac.uk/ols4/ontologies/eco/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FECO_0000000
```

_Percent-number combinations are just HTTP encoded special symbols... it would probably still work if you use slashes, etc. instead but this is how OLS encodes them._

The `prefix` and `replacement` lines tell the redirect engine how to change the URL and the lines below `tests:` are just one or more automated tests to confirm it's working correctly.

I'd recommend going ahead with creating the PR after making the changes. James Overton is usually quick to reply after automated tests complete.


### OBO browser button
The buttons on OBO ontology pages for browsers are controlled separately from PURLs. The ECO page can be edited at https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/eco.md.

To add a browser just do something like [the DO has](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/6fae4d9f67fefd9c9670069f91c6ca58d30bfa3a/ontology/doid.md?plain=1#L6-L8):

```markdown
browsers:
- title: DO Browser
  label: DO
  url: http://www.disease-ontology.org/
```

`label` is what shows up on the page.

_PS. It seems the browser and graphs on https://evidenceontology.org/ are not working, probably because they're using the old OLS URL instead of the new OLS4 URL and they are for some reason unable to follow the redirect that has been put in place by EBI from OLS to OLS4._
