### ISSUE TITLE
HPO evidence types have incorrect values for "GO evidence code"

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#315]
HPO evidence types were added in

- #106

e.g.

```yaml
id: ECO:0006017
name: author statement supported from referenced clinical study used in manual assertion
def: "A type of author statement supported from referenced clinical study that is used in a manual assertion." []
comment: Created and used by the Human Phenotype Ontology (HPO) Annotations group. Here it is used when evidence for an HPO annotation is information extracted from articles in the medical literature.
synonym: "PCS" EXACT [HPO:PCS]
synonym: "published clinical study evidence" BROAD []
is_a: ECO:0000304 {is_inferred="true"} ! author statement supported by traceable reference used in manual assertion
is_a: ECO:0006016 ! author statement supported from referenced clinical study
intersection_of: ECO:0006016 ! author statement supported from referenced clinical study
intersection_of: used_in ECO:0000218 ! manual assertion
property_value: ECO:9000002 "TAS" xsd:string
property_value: seeAlso http://human-phenotype-ontology.github.io/documentation.html#annot xsd:string
```

The value for  ECO:9000002 (GO evidence code) "TAS" is wrong I think. Maybe the intent is to map to the closest GO evidence code? IMO this is not right, only one term in ECO should have the GO code value TAS, which is this one:

```yaml
id: ECO:0000304
name: author statement supported by traceable reference used in manual assertion
def: "A type of author statement supported by traceable reference that is used in a manual assertion." [ECO:MCC]
synonym: "TAS" EXACT [GOECO:TAS]
synonym: "traceable author statement" RELATED [GOECO:TAS]
xref: GOECO:TAS "traceable author statement"
is_a: ECO:0000033 ! author statement supported by traceable reference
is_a: ECO:0000302 {is_inferred="true"} ! author statement used in manual assertion
intersection_of: ECO:0000033 ! author statement supported by traceable reference
intersection_of: used_in ECO:0000218 ! manual assertion
property_value: ECO:9000002 "TAS" xsd:string {comment="Default"}
property_value: seeAlso http://geneontology.org/page/tas-traceable-author-statement xsd:string
```

if people want to roll up to a GO evidence code then they should roll up
